name: "build"

on:
  pull_request:
    branches:
      - "master"
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: "ubuntu-22.04"
    steps:
      - name: "checkout repository"
        uses: "actions/checkout@v3"
      - name: "setup go"
        uses: "actions/setup-go@v3"
        with:
          go-version: "1.20"
      - name: "make test"
        run: "make test"
